# molecules.py

MOLECULES = {
    "He2+": "ZAJTYDXIUNGESO-UHFFFAOYSA-N",
    "H2+": "ZZIJOQHRUPVPQC-UHFFFAOYSA-N",
    "LiH+": "HSOYNNFNUCWPIZ-UHFFFAOYSA-N",
    "MgH+": "LMAKMUADRKEOEM-UHFFFAOYSA-N",
    "NaH+": "FYDBACYJBJQTSN-UHFFFAOYSA-N",
    "HeH+": "HSFAAVLNFOAYQX-UHFFFAOYSA-N",
    "CaH+": "WAJVQHXFGGKNHK-UHFFFAOYSA-N",
}
